import { describe, it, expect } from 'vitest';

import {
  getIdiomMatcher,
  vitestMatcher,
  jestMatcher,
} from '../../../src/generator/idiom-matchers/index.js';

describe('idiom-matchers', () => {
  describe('getIdiomMatcher', () => {
    it('returns the vitest matcher for "vitest"', () => {
      expect(getIdiomMatcher('vitest').framework).toBe('vitest');
    });

    it('returns the jest matcher for "jest"', () => {
      expect(getIdiomMatcher('jest').framework).toBe('jest');
    });

    it('falls back to vitest for unknown frameworks', () => {
      expect(getIdiomMatcher('playwright').framework).toBe('vitest');
      expect(getIdiomMatcher(null).framework).toBe('vitest');
      expect(getIdiomMatcher(undefined).framework).toBe('vitest');
    });
  });

  describe('vitest matcher', () => {
    it('smoke template imports vitest helpers and uses describe/it/expect', () => {
      const rendered = vitestMatcher.templates.smoke.render({
        subject_import_path: './Foo',
        subject_name: 'Foo',
        subject_kind: 'function',
      });
      expect(rendered).toContain(`from 'vitest'`);
      expect(rendered).toContain(`describe('Foo'`);
      expect(rendered).toContain(`it('is defined'`);
      expect(rendered).toContain(`expect(Foo).toBeDefined()`);
    });

    it('smoke template for components imports @testing-library/react', () => {
      const rendered = vitestMatcher.templates.smoke.render({
        subject_import_path: './MovieCard',
        subject_name: 'MovieCard',
        subject_kind: 'component',
      });
      expect(rendered).toContain(`@testing-library/react`);
      expect(rendered).toContain(`render(<MovieCard />)`);
    });

    it('behavioral template includes userEvent for components', () => {
      const rendered = vitestMatcher.templates.behavioral.render({
        subject_import_path: './X',
        subject_name: 'X',
        subject_kind: 'component',
        behavior_hint: 'opens the drawer on click',
      });
      expect(rendered).toContain('userEvent');
      expect(rendered).toContain(`it('opens the drawer on click'`);
    });

    it('integration template uses vi.spyOn for fetch', () => {
      const rendered = vitestMatcher.templates.integration.render({
        subject_import_path: './api',
        subject_name: 'fetchUser',
        subject_kind: 'function',
      });
      expect(rendered).toContain(`vi.spyOn`);
      expect(rendered).toContain(`vi.restoreAllMocks`);
    });

    it('renderHeader carries plugin version, date, confidence, finding id per G2', () => {
      const hdr = vitestMatcher.renderHeader({
        subject_import_path: './X',
        subject_name: 'X',
        subject_kind: 'function',
        plugin_version: '0.2.0',
        iso_date: '2026-04-17',
        confidence_label: 'HIGH',
        finding_id: '#42',
      });
      expect(hdr).toContain('Generated by Vibe Test v0.2.0');
      expect(hdr).toContain('2026-04-17');
      expect(hdr).toContain('Confidence: HIGH');
      expect(hdr).toContain('Audit finding: #42');
    });
  });

  describe('jest matcher', () => {
    it('does not import { describe, it, expect } (jest provides globals)', () => {
      const rendered = jestMatcher.templates.smoke.render({
        subject_import_path: './Foo',
        subject_name: 'Foo',
        subject_kind: 'function',
      });
      expect(rendered).not.toContain(`from 'vitest'`);
      expect(rendered).not.toContain(`from 'jest'`);
      expect(rendered).toContain(`describe('Foo'`);
      expect(rendered).toContain(`expect(Foo).toBeDefined()`);
    });

    it('integration template uses jest.spyOn, not vi.spyOn', () => {
      const rendered = jestMatcher.templates.integration.render({
        subject_import_path: './api',
        subject_name: 'fetchUser',
        subject_kind: 'function',
      });
      expect(rendered).toContain(`jest.spyOn`);
      expect(rendered).not.toContain(`vi.spyOn`);
      expect(rendered).toContain(`jest.restoreAllMocks`);
    });

    it('renderHeader carries required G2 fields', () => {
      const hdr = jestMatcher.renderHeader({
        subject_import_path: './X',
        subject_name: 'X',
        subject_kind: 'function',
        plugin_version: '0.2.0',
        iso_date: '2026-04-17',
        confidence_label: 'MEDIUM',
        finding_id: '#7',
      });
      expect(hdr).toContain('Confidence: MEDIUM');
      expect(hdr).toContain('Audit finding: #7');
    });
  });

  describe('all four levels are exported by each matcher', () => {
    for (const matcher of [vitestMatcher, jestMatcher] as const) {
      it(`${matcher.framework} exposes smoke/behavioral/edge/integration`, () => {
        const levels = Object.keys(matcher.templates).sort();
        expect(levels).toEqual(['behavioral', 'edge', 'integration', 'smoke']);
      });
    }
  });
});
