/**
 * Jest idiom-matcher — framework-specific test-file fragments the SKILL
 * composes into candidate tests at generation time.
 *
 * Shapes mirror the vitest matcher but use jest's global `jest` / `describe` /
 * `it` / `expect` API. No explicit imports for the test harness (jest injects
 * these globally via `jest.setup` / `@types/jest`).
 */

import type { IdiomMatcher, IdiomRenderInput, IdiomTemplate } from './index.js';

const SMOKE: IdiomTemplate = {
  level: 'smoke',
  description: 'Basic render — does the target export/mount without throwing?',
  render: ({ subject_import_path, subject_name, subject_kind }) => {
    if (subject_kind === 'component') {
      return [
        `import { render } from '@testing-library/react';`,
        `import { ${subject_name} } from '${subject_import_path}';`,
        ``,
        `describe('${subject_name}', () => {`,
        `  it('renders without crashing', () => {`,
        `    const { container } = render(<${subject_name} />);`,
        `    expect(container).toBeTruthy();`,
        `  });`,
        `});`,
        '',
      ].join('\n');
    }
    return [
      `import { ${subject_name} } from '${subject_import_path}';`,
      ``,
      `describe('${subject_name}', () => {`,
      `  it('is defined', () => {`,
      `    expect(${subject_name}).toBeDefined();`,
      `  });`,
      `});`,
      '',
    ].join('\n');
  },
};

const BEHAVIORAL: IdiomTemplate = {
  level: 'behavioral',
  description: 'User-facing behavior — click / event / state-change assertion.',
  render: ({ subject_import_path, subject_name, subject_kind, behavior_hint }) => {
    const hint = behavior_hint ?? 'responds to user interaction';
    if (subject_kind === 'component') {
      return [
        `import { render, screen } from '@testing-library/react';`,
        `import userEvent from '@testing-library/user-event';`,
        `import { ${subject_name} } from '${subject_import_path}';`,
        ``,
        `describe('${subject_name}', () => {`,
        `  it('${hint}', async () => {`,
        `    const user = userEvent.setup();`,
        `    render(<${subject_name} />);`,
        `    // TODO: drive interaction, assert on screen query`,
        `    expect(screen).toBeTruthy();`,
        `  });`,
        `});`,
        '',
      ].join('\n');
    }
    return [
      `import { ${subject_name} } from '${subject_import_path}';`,
      ``,
      `describe('${subject_name}', () => {`,
      `  it('${hint}', () => {`,
      `    // TODO: call with representative input, assert on result`,
      `    expect(${subject_name}).toBeDefined();`,
      `  });`,
      `});`,
      '',
    ].join('\n');
  },
};

const EDGE: IdiomTemplate = {
  level: 'edge',
  description: 'Boundary / error-path — empty, max, invalid inputs.',
  render: ({ subject_import_path, subject_name, subject_kind }) => {
    return [
      `import { ${subject_name} } from '${subject_import_path}';`,
      ``,
      `describe('${subject_name} — edges', () => {`,
      `  it('handles empty input', () => {`,
      `    // TODO: call with empty / null / undefined, assert graceful handling`,
      `    expect(${subject_name}).toBeDefined();`,
      `  });`,
      `  it('handles max-boundary input', () => {`,
      `    // TODO: call with max-sized input, assert no throw / correct truncation`,
      `    expect(${subject_kind === 'component' ? 'true' : `${subject_name}`}).toBeTruthy();`,
      `  });`,
      `});`,
      '',
    ].join('\n');
  },
};

const INTEGRATION: IdiomTemplate = {
  level: 'integration',
  description: 'Integration — mocked fetch / API / third-party.',
  render: ({ subject_import_path, subject_name }) => {
    return [
      `import { ${subject_name} } from '${subject_import_path}';`,
      ``,
      `describe('${subject_name} — integration', () => {`,
      `  beforeEach(() => {`,
      `    jest.spyOn(globalThis, 'fetch').mockResolvedValue(`,
      `      new Response(JSON.stringify({ ok: true }), { status: 200 }) as never,`,
      `    );`,
      `  });`,
      `  afterEach(() => {`,
      `    jest.restoreAllMocks();`,
      `  });`,
      `  it('makes the expected request and handles the response', async () => {`,
      `    // TODO: invoke ${subject_name}, assert on mock call args + resolved value`,
      `    expect(globalThis.fetch).toBeDefined();`,
      `  });`,
      `});`,
      '',
    ].join('\n');
  },
};

export const jestMatcher: IdiomMatcher = {
  framework: 'jest',
  templates: {
    smoke: SMOKE,
    behavioral: BEHAVIORAL,
    edge: EDGE,
    integration: INTEGRATION,
  },
  renderHeader(input: IdiomRenderInput & {
    plugin_version: string;
    iso_date: string;
    confidence_label: 'HIGH' | 'MEDIUM' | 'LOW';
    finding_id: string;
  }): string {
    return [
      `// Generated by Vibe Test v${input.plugin_version} on ${input.iso_date}.`,
      `// Confidence: ${input.confidence_label}. Audit finding: ${input.finding_id}.`,
      '',
    ].join('\n');
  },
};
